version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=ram
      - MONGO_PASSWORD=test

    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ram
      - MONGO_INITDB_ROOT_PASSWORD=test
